# Numpy 

- Array from numpy

### Difference between array and list

# Array

- An array is a collection of homogenous data-types.
- 4 byte
- Array can store data very compactly and more effcient for storing large amount of data.
- Array are great for numerical operations, list cannot directly handle math operations
- As the array size increases, numpy array get around 30 times faster than python list.
- Because the numpy array is denely packed in memory due to homogeous type, also frees the memory faster.
- you have to explicity import nupy to use array

# List

- wheras list is a collection of hetrogeneous data-types 
- 14 byte
- List less effcient than array for storing large amount of data.
- its is python data type


In [ ]:
l=["sarthk",1,2,True]

In [ ]:
array=[1,2,3,5]

In [2]:
import numpy as np

In [8]:
my_list=["ram",123,50.5,7+2j]
print(my_list)
type(my_list)
# wheras list is a collection of hetrogeneous data-types 

['ram', 123, 50.5, (7+2j)]


list

## create array

In [6]:
a=np.array([[[1,2,3,6,9]]])
print(a)
type(a)

[[[1 2 3 6 9]]]


numpy.ndarray

In [7]:
a.ndim

3

In [10]:
my_array=np.array(["ram",123,50.5,7+2j])
print(my_array)
type(my_array)
# An array is a collection of homogenous data-types.

['ram' '123' '50.5' '(7+2j)']


numpy.ndarray

In [12]:
my_array=np.array([123,50.5,7+2j]) #int,float,complex
print(my_array)
type(my_array)

[123. +0.j  50.5+0.j   7. +2.j]


numpy.ndarray

## string > Complex > float > int

In [13]:
x=np.array([123,"sarthak","chetana",45.7]) 
print(x)
type(x)

['123' 'sarthak' 'chetana' '45.7']


numpy.ndarray

In [15]:
x=np.array([123,2+4j,45.7,2]) #int,float,complex
print(x)
type(x)

[123. +0.j   2. +4.j  45.7+0.j   2. +0.j]


numpy.ndarray

In [16]:
my_array=np.array([123,50.5])
print(my_array)
type(my_array)

[123.   50.5]


numpy.ndarray

# Empty Numpy array

In [17]:
a=np.array([])
a

array([], dtype=float64)

### Atrributes of Numpy

In [ ]:
Attributes:

ndarray.ndim: The number of dimensions (axes) of the array.
ndarray.shape: A tuple representing the dimensions of the array, e.g., (rows, columns) for a 2D array.
ndarray.size: The total number of elements in the array.
ndarray.dtype: The data type of elements in the array.
ndarray.itemsize: The size in bytes of each element in the array.
ndarray.data: A buffer containing the actual elements of the array.

### 1.ndim

In [21]:
x=np.array([[123,"sarthak","chetana",45.7],[1,2,3,4]]) 
print(x)

[['123' 'sarthak' 'chetana' '45.7']
 ['1' '2' '3' '4']]


In [22]:
x.ndim

2

In [11]:
x=np.array([[123,45,45,60],[1,2,3,4],[10,20,30,12.23]]) 
print(x)

[[123.    45.    45.    60.  ]
 [  1.     2.     3.     4.  ]
 [ 10.    20.    30.    12.23]]


In [35]:
x.ndim

2

### 2.shape

In [36]:
x.shape

(3, 4)

### 3.size

In [37]:
x.size

12

### 4.dtype

In [40]:
x.dtype

dtype('float64')

### 5. itemsize

In [42]:
x.itemsize

8

In [43]:
x.data

### 6.dtpye

In [5]:
a=np.array([[1,2,34],[1,2,3]])
print(a)


[[ 1  2 34]
 [ 1  2  3]]


In [6]:
a.dtype

dtype('int32')

In [7]:
a=np.array([[1,2,34],[1,2,3]],dtype=str)
print(a)

[['1' '2' '34']
 ['1' '2' '3']]


In [8]:
a=np.array([[1,2,34],[1,2,3]],dtype=complex)
print(a)

[[ 1.+0.j  2.+0.j 34.+0.j]
 [ 1.+0.j  2.+0.j  3.+0.j]]


### 7.data

In [12]:
x.data

### Array Creation Functions:

### 1.np.array()

In [46]:
a_list=np.array([["a","b","c","d"],["x","y","z","p"]])
print(a_list)

[['a' 'b' 'c' 'd']
 ['x' 'y' 'z' 'p']]


In [47]:
b_tuple=np.array([("a","b","c","d"),("x","y","z","p")])
print(b_tuple)

[['a' 'b' 'c' 'd']
 ['x' 'y' 'z' 'p']]


In [51]:
b_tuple.shape

(2, 4)

### 2. np.zeros()

In [14]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 3.zeros_like()

In [13]:
a_list=np.array([[[1,2,3,6],[4,8,7,9],[4,8,9,7]]])
print(a_list)

[[[1 2 3 6]
  [4 8 7 9]
  [4 8 9 7]]]


In [59]:
a_list.ndim

3

In [60]:
np.zeros_like(a_list)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

### 4.ones()

In [67]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### 5.ones_like

In [69]:
y=np.array([[1,2,3,4],[5,6,7,8]])
print(y)

[[1 2 3 4]
 [5 6 7 8]]


In [70]:
np.ones_like(y)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

### 6 np.empty()

In [6]:
np.empty(0)

array([], dtype=float64)

In [7]:
np.empty(5)

array([0.00000000e+000, 9.57866110e-312, 9.57866109e-312, 9.57866109e-312,
       6.95271921e-310])

### 7.np.arange()

In [2]:
for i in range(1,19,3):  #range(start,stop,step)
    print(i)

1
4
7
10
13
16


In [84]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [4]:
import numpy as np

### 8.np.linspace()

In [12]:
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

### 9.np.logspace()

In [10]:
np.logspace(1,10,5)

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

### Array Manipulation Functions:

### 1. reshape()

In [13]:
a_list=np.array([[1,2,3,6],[4,8,7,9],[4,8,9,7]])
a_list

array([[1, 2, 3, 6],
       [4, 8, 7, 9],
       [4, 8, 9, 7]])

In [14]:
#12=(2,6),(4,3),(12,1)

In [17]:
a_list.reshape(6,2)

array([[1, 2],
       [3, 6],
       [4, 8],
       [7, 9],
       [4, 8],
       [9, 7]])

In [25]:
a_list.shape

(3, 4)

### 2.Transpose()

In [32]:
y=np.array([[1,2,3,4],[5,6,7,8]])
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
y.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### 3.concatinate()

In [39]:
np.concatenate(a_list)

array([1, 2, 3, 6, 4, 8, 7, 9, 4, 8, 9, 7])

In [38]:
np.concatenate(y)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
vstack()

In [41]:
np.vstack(y)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [44]:
a_list

array([[1, 2, 3, 6],
       [4, 8, 7, 9],
       [4, 8, 9, 7]])

In [43]:
np.hstack(a_list)

array([1, 2, 3, 6, 4, 8, 7, 9, 4, 8, 9, 7])

In [45]:
np.vstack(a_list)

array([[1, 2, 3, 6],
       [4, 8, 7, 9],
       [4, 8, 9, 7]])

### 4.split()

In [18]:
a_list

array([[1, 2, 3, 6],
       [4, 8, 7, 9],
       [4, 8, 9, 7]])

In [19]:
e=np.arange(0,10)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.split(e,(5))

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [21]:
np.split(e,(3))

ValueError: array split does not result in an equal division

In [34]:
e1=np.arange(0,9)
e1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
np.split(e1,(3))

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

### 5.delete()

In [38]:
a=np.array([12,2,3,4,65])

In [40]:
np.delete(a,4)

array([12,  2,  3,  4])

### Mathematical Functions:

In [41]:
a_list

array([[1, 2, 3, 6],
       [4, 8, 7, 9],
       [4, 8, 9, 7]])

In [44]:
b_list=np.array([[10,20,30,40],[50,30,20,10],[60,70,40,30]])
b_list

array([[10, 20, 30, 40],
       [50, 30, 20, 10],
       [60, 70, 40, 30]])

In [81]:
np.add(a_list,b_list)

array([[11, 22, 33, 46],
       [54, 38, 27, 19],
       [64, 78, 49, 37]])

In [82]:
b_list+a_list

array([[11, 22, 33, 46],
       [54, 38, 27, 19],
       [64, 78, 49, 37]])

### sum()

In [85]:
b_list.sum()

410

# indexing and slicing

### indexing of 2D array

In [90]:
a=np.array([[5,2,34],[1,2,3]])
a.ndim

2

In [88]:
a[0][1]

2

In [89]:
a[1][0]

1

### Indexing of 3D array

# Creating Randome numbers

In [47]:
np.random.rand(4)

array([0.04685804, 0.98752414, 0.15573732, 0.16095827])

In [48]:
np.random.rand(4,4)

array([[0.59848076, 0.49023482, 0.30645057, 0.85351532],
       [0.89189523, 0.481379  , 0.74408016, 0.9794255 ],
       [0.54506217, 0.10622609, 0.23509714, 0.60919576],
       [0.75035992, 0.84401537, 0.44049694, 0.65970377]])

In [51]:
a=np.random.rand(1,4,3)  #(matrix,rows,column)
print(a)
a.ndim

[[[0.94301294 0.8359601  0.56919846]
  [0.37152763 0.03207619 0.71529671]
  [0.90467643 0.82889279 0.17168393]
  [0.48404723 0.43088244 0.74989085]]]


3

In [76]:
a=np.random.rand(4,4,4,4)
print(a)
a.ndim

[[[[0.41492615 0.51400063 0.10982649 0.36308527]
   [0.28568396 0.52464685 0.95224734 0.99807194]
   [0.126213   0.64411998 0.45428341 0.73134935]
   [0.15904399 0.01185817 0.29930359 0.1016113 ]]

  [[0.01871363 0.43848333 0.19997603 0.97259143]
   [0.29373174 0.44871272 0.83535391 0.44593944]
   [0.89140984 0.28104702 0.79266171 0.58389265]
   [0.60927516 0.54086742 0.99934652 0.93916834]]

  [[0.60692252 0.35482219 0.29783923 0.45753373]
   [0.21792085 0.3610872  0.21445462 0.36788153]
   [0.24693284 0.01560877 0.46586464 0.7886885 ]
   [0.25308053 0.17122519 0.34340964 0.27751701]]

  [[0.58902064 0.74597193 0.32284388 0.03997302]
   [0.47900998 0.96052148 0.7100521  0.92266857]
   [0.64650494 0.27289356 0.04763421 0.20861965]
   [0.52401402 0.73742586 0.11769386 0.95076659]]]


 [[[0.14647379 0.72999165 0.30408157 0.23159779]
   [0.8682752  0.15600891 0.28087444 0.79511983]
   [0.03429402 0.60284717 0.30220668 0.62713611]
   [0.34094172 0.45151528 0.62731441 0.75904731]]

  [[0.95

4

In [77]:
np.random.randint(1,10,(5,5))

array([[9, 4, 7, 3, 4],
       [7, 2, 2, 6, 6],
       [6, 3, 4, 8, 5],
       [1, 4, 3, 6, 9],
       [4, 6, 8, 3, 8]])

In [82]:
np.random.randint(1,100,(5,2))

array([[14, 92],
       [84, 54],
       [70,  3],
       [85, 99],
       [29, 84]])

# Reshape

In [84]:
a=np.random.randint(1,100,(5,10))
a

array([[20,  7, 98, 56, 52, 48, 54, 33, 67, 13],
       [60, 79, 44, 68, 27, 89, 34, 47, 45, 67],
       [50, 90, 25, 26, 38, 72, 73, 62,  8, 49],
       [28, 51,  7, 86, 95, 37, 53, 43, 78, 58],
       [30, 96, 15, 15, 23, 53, 58, 16, 94, 89]])

In [ ]:
50
50 *1
25*2
10*5

In [88]:
b=a.reshape(25,2)
b

array([[20,  7],
       [98, 56],
       [52, 48],
       [54, 33],
       [67, 13],
       [60, 79],
       [44, 68],
       [27, 89],
       [34, 47],
       [45, 67],
       [50, 90],
       [25, 26],
       [38, 72],
       [73, 62],
       [ 8, 49],
       [28, 51],
       [ 7, 86],
       [95, 37],
       [53, 43],
       [78, 58],
       [30, 96],
       [15, 15],
       [23, 53],
       [58, 16],
       [94, 89]])

In [89]:
b=a.reshape(10,5)
b

array([[20,  7, 98, 56, 52],
       [48, 54, 33, 67, 13],
       [60, 79, 44, 68, 27],
       [89, 34, 47, 45, 67],
       [50, 90, 25, 26, 38],
       [72, 73, 62,  8, 49],
       [28, 51,  7, 86, 95],
       [37, 53, 43, 78, 58],
       [30, 96, 15, 15, 23],
       [53, 58, 16, 94, 89]])

In [90]:
a=np.random.randint(1,100,(1,100))
a

array([[76, 59, 25, 97, 45, 15, 82, 77, 10, 91, 26, 90, 16, 55, 53, 91,
        15, 65, 89, 45, 98, 95, 56, 38, 30, 98, 98, 89, 74,  7, 36,  5,
        22, 62, 58,  1, 95, 23, 13, 96, 16,  7, 31,  7, 94, 48, 54, 29,
        36, 43, 90, 28, 51, 55, 87, 15, 56, 27, 69, 27, 83, 11, 55,  6,
        40, 15, 68, 63, 56, 35, 39, 45, 70, 55, 83, 47, 62, 32, 77, 39,
        91, 51, 25,  5, 93, 53, 82, 12, 56, 87,  9,  6, 59,  5, 57, 98,
        92, 26, 28, 52]])

In [ ]:
10*10
25*4
50*2
100*1
20*5

In [96]:
b=a.reshape(5,20)
b

array([[76, 59, 25, 97, 45, 15, 82, 77, 10, 91, 26, 90, 16, 55, 53, 91,
        15, 65, 89, 45],
       [98, 95, 56, 38, 30, 98, 98, 89, 74,  7, 36,  5, 22, 62, 58,  1,
        95, 23, 13, 96],
       [16,  7, 31,  7, 94, 48, 54, 29, 36, 43, 90, 28, 51, 55, 87, 15,
        56, 27, 69, 27],
       [83, 11, 55,  6, 40, 15, 68, 63, 56, 35, 39, 45, 70, 55, 83, 47,
        62, 32, 77, 39],
       [91, 51, 25,  5, 93, 53, 82, 12, 56, 87,  9,  6, 59,  5, 57, 98,
        92, 26, 28, 52]])

# Zeros

In [ ]:
# Return a new array of given shape and type, filled with zeros.

In [98]:
np.zeros((9))

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [99]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [97]:
np.zeros((9,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [100]:
np.zeros_like(b)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# Ones

Return a new array of given shape and type, filled with ones.

In [101]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [102]:
np.ones_like(b)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

# Full

Return a new array of given shape and type, filled with fill_value.

In [103]:
np.full((5,5),100)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [105]:
np.full((4,8),"mS")

array([['mS', 'mS', 'mS', 'mS', 'mS', 'mS', 'mS', 'mS'],
       ['mS', 'mS', 'mS', 'mS', 'mS', 'mS', 'mS', 'mS'],
       ['mS', 'mS', 'mS', 'mS', 'mS', 'mS', 'mS', 'mS'],
       ['mS', 'mS', 'mS', 'mS', 'mS', 'mS', 'mS', 'mS']], dtype='<U2')

In [106]:
np.full_like(b,15)

array([[15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15]])

# eye

- Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [107]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [108]:
np.eye(5,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

In [109]:
np.eye(10,10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [112]:
np.eye(10,k=4)

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [115]:
np.eye(10,k=-2)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]])

# arange()

In [116]:
range(1,10)

range(1, 10)

In [117]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [118]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [119]:
list(range(1,10,2.5))

TypeError: 'float' object cannot be interpreted as an integer

In [120]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [125]:
np.arange(1,51).reshape(2,25)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44, 45, 46, 47, 48, 49, 50]])

# LineSpace

Return evenly spaced numbers over a specified interval.

Returns num evenly spaced samples, calculated over the interval [start, stop].

The endpoint of the interval can optionally be excluded.


In [130]:
np.linspace(1,100,30)

array([  1.        ,   4.4137931 ,   7.82758621,  11.24137931,
        14.65517241,  18.06896552,  21.48275862,  24.89655172,
        28.31034483,  31.72413793,  35.13793103,  38.55172414,
        41.96551724,  45.37931034,  48.79310345,  52.20689655,
        55.62068966,  59.03448276,  62.44827586,  65.86206897,
        69.27586207,  72.68965517,  76.10344828,  79.51724138,
        82.93103448,  86.34482759,  89.75862069,  93.17241379,
        96.5862069 , 100.        ])

In [131]:
np.linspace(1,100,30, endpoint=False)

array([ 1. ,  4.3,  7.6, 10.9, 14.2, 17.5, 20.8, 24.1, 27.4, 30.7, 34. ,
       37.3, 40.6, 43.9, 47.2, 50.5, 53.8, 57.1, 60.4, 63.7, 67. , 70.3,
       73.6, 76.9, 80.2, 83.5, 86.8, 90.1, 93.4, 96.7])

In [132]:
np.linspace(1,100,30, endpoint=False,retstep=True)

(array([ 1. ,  4.3,  7.6, 10.9, 14.2, 17.5, 20.8, 24.1, 27.4, 30.7, 34. ,
        37.3, 40.6, 43.9, 47.2, 50.5, 53.8, 57.1, 60.4, 63.7, 67. , 70.3,
        73.6, 76.9, 80.2, 83.5, 86.8, 90.1, 93.4, 96.7]),
 3.3)

In [134]:
np.linspace(1,1000,70)

array([   1.        ,   15.47826087,   29.95652174,   44.43478261,
         58.91304348,   73.39130435,   87.86956522,  102.34782609,
        116.82608696,  131.30434783,  145.7826087 ,  160.26086957,
        174.73913043,  189.2173913 ,  203.69565217,  218.17391304,
        232.65217391,  247.13043478,  261.60869565,  276.08695652,
        290.56521739,  305.04347826,  319.52173913,  334.        ,
        348.47826087,  362.95652174,  377.43478261,  391.91304348,
        406.39130435,  420.86956522,  435.34782609,  449.82608696,
        464.30434783,  478.7826087 ,  493.26086957,  507.73913043,
        522.2173913 ,  536.69565217,  551.17391304,  565.65217391,
        580.13043478,  594.60869565,  609.08695652,  623.56521739,
        638.04347826,  652.52173913,  667.        ,  681.47826087,
        695.95652174,  710.43478261,  724.91304348,  739.39130435,
        753.86956522,  768.34782609,  782.82608696,  797.30434783,
        811.7826087 ,  826.26086957,  840.73913043,  855.21739

# Logspace


- Return numbers spaced evenly on a log scale.
- LOG-BASE10



In [135]:
np.logspace(1,100)

array([1.00000000e+001, 1.04811313e+003, 1.09854114e+005, 1.15139540e+007,
       1.20679264e+009, 1.26485522e+011, 1.32571137e+013, 1.38949549e+015,
       1.45634848e+017, 1.52641797e+019, 1.59985872e+021, 1.67683294e+023,
       1.75751062e+025, 1.84206997e+027, 1.93069773e+029, 2.02358965e+031,
       2.12095089e+033, 2.22299648e+035, 2.32995181e+037, 2.44205309e+039,
       2.55954792e+041, 2.68269580e+043, 2.81176870e+045, 2.94705170e+047,
       3.08884360e+049, 3.23745754e+051, 3.39322177e+053, 3.55648031e+055,
       3.72759372e+057, 3.90693994e+059, 4.09491506e+061, 4.29193426e+063,
       4.49843267e+065, 4.71486636e+067, 4.94171336e+069, 5.17947468e+071,
       5.42867544e+073, 5.68986603e+075, 5.96362332e+077, 6.25055193e+079,
       6.55128557e+081, 6.86648845e+083, 7.19685673e+085, 7.54312006e+087,
       7.90604321e+089, 8.28642773e+091, 8.68511374e+093, 9.10298178e+095,
       9.54095476e+097, 1.00000000e+100])

# Where

In [140]:
z=np.arange(3,50)
z

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [144]:
np.where(z<15)

# it gives position of that element wch satisfy the condition

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64),)

In [142]:
np.where(z%2==0)

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
        35, 37, 39, 41, 43, 45], dtype=int64),)

In [143]:
np.where(z==6)

(array([3], dtype=int64),)

# Split

Split an array into multiple sub-arrays 

In [145]:
e=np.arange(0,10)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
np.split(e,5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [149]:
np.split(e,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [150]:
a,b=np.split(e,2)

In [151]:
a

array([0, 1, 2, 3, 4])

In [152]:
b

array([5, 6, 7, 8, 9])

# Airththematic Operations in numpy

In [153]:
a=np.array([[1,2,10],[5,7,8]])
b=np.array([[10,20,7],[50,70,7]])

In [154]:
a

array([[ 1,  2, 10],
       [ 5,  7,  8]])

In [155]:
b

array([[10, 20,  7],
       [50, 70,  7]])

In [156]:
np.add(a,b)

array([[11, 22, 17],
       [55, 77, 15]])

In [158]:
np.subtract(a,b)

array([[ -9, -18,   3],
       [-45, -63,   1]])

In [159]:
np.multiply(a,b)

array([[ 10,  40,  70],
       [250, 490,  56]])

In [160]:
np.divide(a,b)

array([[0.1       , 0.1       , 1.42857143],
       [0.1       , 0.1       , 1.14285714]])

In [161]:
np.mod(a,b)

array([[1, 2, 3],
       [5, 7, 1]], dtype=int32)

In [162]:
np.power(a,b)

array([[         1,    1048576,   10000000],
       [1296002393, 1187094929,    2097152]], dtype=int32)

# Statistics

In [163]:
s=np.array([[50,10,30,],[500,100,300,],[5,1,3,]])
s

array([[ 50,  10,  30],
       [500, 100, 300],
       [  5,   1,   3]])

In [164]:
np.amin(s)

1

In [165]:
np.amax(s)

500

In [166]:
np.amax(s,axis=0)

array([500, 100, 300])

In [167]:
np.amax(s,axis=1)

array([ 50, 500,   5])

In [168]:
np.mean(s)

111.0

In [169]:
np.var(s)

26960.666666666668

In [170]:
np.std(s)

164.1970361080451

# Datatype

### The main several data types supported by NumPy Python are:

    np.bool_: This type is used to return boolean values like (True or False).
    np.int: It is the default type of integer and C-type long.
    intc: It is similar to C integer and it indicates 32 or 64 bit integer.
    intp: This type indicates for indexing.
    int8: By default its range value is -128 to 127.
    int16: It is a 16 bit integer and by default its range value is (-32768 to 32767).
    int32: it is for set 32-bit integer and the range value is (-2147483648 to 2147483647).
    int64: By default its value is set at (-9223372036854775808 to 9223372036854775807).
    uint8: It is a 8 bit integer and range value is (0 to 255).
    uint16: It is a 16 bit unsigned integer and range value is (0 to 65535).
    uint32: This is a unsigned integer with 32 bit and its value is (0 to 4294967295).
    uint64: It is a 8 byte unsigned integer and range value is (0 to 18446744073709551615).

In [172]:
a=np.array([2555])
a.dtype

dtype('int32')

In [176]:
a=np.array([12,2,3,6],dtype=np.float16)
a.dtype

dtype('float16')

In [177]:
a

array([12.,  2.,  3.,  6.], dtype=float16)

In [178]:
np.array(np.datetime64('1999-06-14'))

array('1999-06-14', dtype='datetime64[D]')

In [182]:
new=np.array([1.0,2.0,3.0])
new

array([1., 2., 3.])

In [183]:
b=np.array([1,2,3])

In [189]:
b.astype("str")

array(['1', '2', '3'], dtype='<U11')

In [190]:
b.astype("f")

array([1., 2., 3.], dtype=float32)

In [193]:
np.iinfo(np.int8).max

127

In [194]:
np.iinfo(np.int8).min

-128

In [55]:
l=np.array([[7,19,3],[4,21,0]])
l

array([[ 7, 19,  3],
       [ 4, 21,  0]])

In [ ]:
for i 