### Numpy

- Aarry from numpy

### Array

- An Array is a collection of homogenous data-types. (String data type)
- 4 byte
- Array can store data very compactly and more effcient for storing large amount of data.
- Array are great for numerical operations, list cannot directly handle math operations
- As the array size increases, numpy array get around 30 times faster than python list.
- Because the numpy array is denely packed in memory due to homogeous type, also frees the memory faster.
- you have to explicity import nupy to use array

### List

- wheras list is a collection of hetrogeneous data-types
- 14 byte
- List less effcient than array for storing large amount of data.
- its is python data type

In [5]:
import numpy as np

In [8]:
my_list=["ram",123,50.5,7+2j]
print(my_list)
type(my_list)
#whereas list is a collction of hetrogeneous data-types

['ram', 123, 50.5, (7+2j)]


list

In [9]:
my_array=np.array(["ram",123,50.5,7+2j])
print(my_array)
type(my_array)
#An array is a collection of hetrogeneous data-types

['ram' '123' '50.5' '(7+2j)']


numpy.ndarray

In [10]:
my_array=np.array([123,50.5])
print(my_array)
type(my_array)

[123.   50.5]


numpy.ndarray

### string>complex>float>int

#### Empty Numpy array

In [13]:
import numpy as np

In [15]:
a=np.array([])
a

array([], dtype=float64)

In [16]:
my_array=np.array([[123,50.0],[1,2]])
print(my_array)
type(my_array)

[[123.  50.]
 [  1.   2.]]


numpy.ndarray

### 1.ndim

In [17]:
# to Check dimension
my_array.ndim

2

In [19]:
a=np.array([1,2,34])
print(a)
print("the dim is:",a.ndim)

[ 1  2 34]
the dim is: 1


In [23]:
a=np.array([[[1,2,34],[1,2,3]]])
print(a)
print("the dim is:",a.ndim)

[[[ 1  2 34]
  [ 1  2  3]]]
the dim is: 3


In [24]:
a=np.array([[[1,2,34],[1,2,3],[1,2,3]]])
print(a)
print("the dim is:",a.ndim)

[[[ 1  2 34]
  [ 1  2  3]
  [ 1  2  3]]]
the dim is: 3


In [ ]:
Type Markdown and Latex:

### 2.dtype

In [27]:
a=np.array([[1,2,34],[1,2,3]],dtype=str)      #dtype:
print(a)
print("the dim is:",a.ndim)

[['1' '2' '34']
 ['1' '2' '3']]
the dim is: 2


In [28]:
a=np.array([[1,2,34],[1,2,3]],dtype=float)      
print(a)
print("the dim is:",a.ndim)

[[ 1.  2. 34.]
 [ 1.  2.  3.]]
the dim is: 2


In [29]:
a=np.array([[1,2,34],[1,2,3]],dtype=complex)     
print(a)
print("the dim is:",a.ndim)

[[ 1.+0.j  2.+0.j 34.+0.j]
 [ 1.+0.j  2.+0.j  3.+0.j]]
the dim is: 2


In [30]:
a=np.array([[1,2,34],[1,2,3]],dtype=int)      #dtype:
print(a)
print("the dim is:",a.ndim)

[[ 1  2 34]
 [ 1  2  3]]
the dim is: 2


In [34]:
a=np.array([[5,2,34.3],[1,2,3]])
print(a)
print("the dim is:",a.ndim)

[[ 5.   2.  34.3]
 [ 1.   2.   3. ]]
the dim is: 2


In [36]:
a.dtype

dtype('float64')

### 3.itemsize

In [38]:
a.itemsize

8

### 4.shape

In [39]:
a.shape

(2, 3)

### 5.size

In [40]:
a.size

6

### 6.data

In [41]:
a.data

### indexing and slicing

In [44]:
a=np.array([[5,2,34],[1,2,3]])

In [46]:
a.ndim

2

In [47]:
a[0][0]

5

In [48]:
a[0][2]

34

In [49]:
a[1][0]

1

In [51]:
a=np.array([[[1,2,3,4,5,6],[11,22,33,44,55,66]],[[111,222,333,444,555,666],[1111,2222,3333,4444,5555,6666]]])
print(a)
a.ndim

[[[   1    2    3    4    5    6]
  [  11   22   33   44   55   66]]

 [[ 111  222  333  444  555  666]
  [1111 2222 3333 4444 5555 6666]]]


3

In [52]:
a[0]

array([[ 1,  2,  3,  4,  5,  6],
       [11, 22, 33, 44, 55, 66]])

In [53]:
a[0][0]

array([1, 2, 3, 4, 5, 6])

In [54]:
a[0][1]

array([11, 22, 33, 44, 55, 66])

In [55]:
a[1][1][-1]

6666

In [56]:
a[1:,1:,-1:]

array([[[6666]]])

In [59]:
a[0:1,0:1,1:3]

array([[[2, 3]]])

In [62]:
a=np.array([[[1,2,3,4,5,6]]])
print(a)
a.ndim

[[[1 2 3 4 5 6]]]


3

In [63]:
a[0][0][-1]

6

### Creating Randome Numbers

In [64]:
np.random.rand(5)

array([0.43343277, 0.59836273, 0.27181081, 0.71562516, 0.37545497])

In [65]:
np.random.rand(4,5)

array([[0.36970552, 0.59737674, 0.46391061, 0.92944626, 0.75826169],
       [0.91034772, 0.86794024, 0.38270368, 0.29916758, 0.60394072],
       [0.40196415, 0.71904882, 0.46489179, 0.87214482, 0.88263133],
       [0.52869854, 0.21918124, 0.27079977, 0.19189409, 0.54300428]])

### Numpy Functions()

- numpy.linspace: Create an array spaced values over a specified range.
- numpy.logsapce: create an array spaced values on a logarithmic scale.

### 1.array()

In [67]:
a=np.array([[5,2,34.3],[1,2,3]])
a

array([[ 5. ,  2. , 34.3],
       [ 1. ,  2. ,  3. ]])

### 2.zeros()

In [68]:
np.zeros((9,6))      #zeros(rows,colums)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [69]:
np.zeros_like(a)

array([[0., 0., 0.],
       [0., 0., 0.]])

### 3..ones()

In [70]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [71]:
np.ones_like(a)

array([[1., 1., 1.],
       [1., 1., 1.]])

### 4.empty()

In [72]:
np.empty([])

array(1.)

### 5.arrage()

In [76]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

### 6.linespace()

In [77]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

### 7.logspace()

- Return number spaced evenly on a log scale
- LOG-Base10

In [85]:
np.logspace(1,10,2)

array([1.e+01, 1.e+10])

### Manipulation Functions

In [86]:
a=np.array([[5,2,34.3],[1,2,3]])
a

array([[ 5. ,  2. , 34.3],
       [ 1. ,  2. ,  3. ]])

## reshape()

In [87]:
a=np.random.randint(1,10,(5,10))

In [88]:
a

array([[1, 4, 8, 6, 8, 9, 9, 6, 3, 2],
       [9, 8, 6, 9, 2, 6, 2, 8, 4, 8],
       [8, 5, 6, 7, 2, 5, 9, 1, 7, 8],
       [4, 5, 4, 2, 9, 2, 7, 4, 5, 6],
       [9, 5, 2, 2, 4, 6, 9, 2, 7, 7]])

In [89]:
b=a.reshape(25,2)
b

array([[1, 4],
       [8, 6],
       [8, 9],
       [9, 6],
       [3, 2],
       [9, 8],
       [6, 9],
       [2, 6],
       [2, 8],
       [4, 8],
       [8, 5],
       [6, 7],
       [2, 5],
       [9, 1],
       [7, 8],
       [4, 5],
       [4, 2],
       [9, 2],
       [7, 4],
       [5, 6],
       [9, 5],
       [2, 2],
       [4, 6],
       [9, 2],
       [7, 7]])

### 2.Transpose()

In [145]:
y=np.array([[1,2,3,4],[5,6,7,8]])
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [146]:
y.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### 3.concatinate()

In [148]:
a

array([[1, 2, 3],
       [2, 3, 4]])

In [149]:
np.concatenate(a)

array([1, 2, 3, 2, 3, 4])

In [150]:
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [151]:
np.concatenate(y)

array([1, 2, 3, 4, 5, 6, 7, 8])

### vstack()

In [152]:
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [153]:
np.vstack(y)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [155]:
np.hstack(y)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [156]:
a

array([[1, 2, 3],
       [2, 3, 4]])

In [157]:
np.vstack(a)

array([[1, 2, 3],
       [2, 3, 4]])

In [159]:
np.hstack(a)

array([1, 2, 3, 2, 3, 4])

In [90]:
a=np.random.rand(4,4,4)
print(a)
a.ndim

[[[0.3398026  0.22607574 0.3447382  0.51510902]
  [0.32238975 0.14457817 0.11337277 0.13687243]
  [0.98803829 0.29190609 0.08433543 0.42362064]
  [0.40964435 0.72438956 0.0967185  0.60875795]]

 [[0.37180209 0.14260781 0.8916892  0.76376465]
  [0.5202886  0.28788539 0.11363173 0.20155217]
  [0.84051029 0.47755814 0.74460022 0.77752214]
  [0.90676098 0.02350712 0.75554379 0.13990166]]

 [[0.99245849 0.41471858 0.8995705  0.87578005]
  [0.76820925 0.35975003 0.86305749 0.8294315 ]
  [0.96504597 0.77475599 0.02199981 0.25963356]
  [0.77115699 0.62060126 0.4342089  0.21929632]]

 [[0.33185728 0.74521985 0.97570356 0.91049631]
  [0.89655305 0.48328517 0.5967062  0.20530177]
  [0.39827156 0.07317853 0.68926081 0.45564676]
  [0.07850827 0.74306036 0.37269485 0.20624021]]]


3

In [91]:
np.random.randint(1,10,(2,3))  #randint(range,(rows,col))

array([[7, 4, 9],
       [9, 2, 7]])

In [93]:
x=np.random.randint(1,10,(6,6))  #36=(2,18),(3,12),(12,3)
x

array([[6, 3, 1, 1, 1, 7],
       [3, 7, 5, 3, 7, 5],
       [9, 5, 4, 2, 3, 8],
       [5, 7, 5, 1, 6, 5],
       [8, 8, 4, 8, 6, 8],
       [9, 5, 4, 8, 5, 1]])

In [94]:
x.reshape(12,3)

array([[6, 3, 1],
       [1, 1, 7],
       [3, 7, 5],
       [3, 7, 5],
       [9, 5, 4],
       [2, 3, 8],
       [5, 7, 5],
       [1, 6, 5],
       [8, 8, 4],
       [8, 6, 8],
       [9, 5, 4],
       [8, 5, 1]])

In [95]:
x.reshape(2,18)

array([[6, 3, 1, 1, 1, 7, 3, 7, 5, 3, 7, 5, 9, 5, 4, 2, 3, 8],
       [5, 7, 5, 1, 6, 5, 8, 8, 4, 8, 6, 8, 9, 5, 4, 8, 5, 1]])

In [96]:
np.random.randint(1,100,(5,2))

array([[50, 17],
       [95, 50],
       [61, 64],
       [ 3, 29],
       [ 4, 55]])

In [98]:
a=np.random.randint(1,100,(1,100))
a

array([[79, 65, 77, 61, 50, 34, 66, 77, 46, 59, 89, 33, 12, 91, 64, 14,
        63, 62,  1, 61, 47, 42, 21, 38, 64, 24, 95, 23, 59,  3, 59, 12,
        64, 78, 41, 17, 55, 22, 35, 85, 36, 30,  8, 73, 31, 80, 12, 59,
        14, 48, 67, 99, 35, 98, 94, 84, 96, 29, 28, 68, 94,  8,  3, 14,
        66, 52, 54, 68, 10, 83, 97, 48,  1, 82, 65,  4, 41, 33, 67, 23,
        97, 89, 23, 80, 76, 22,  6, 27, 19, 35, 42, 65, 29, 76, 65, 52,
         5, 11, 13,  4]])

## Full

- Return a new array of given shape and types,filled with fill_value.

In [99]:
np.full((5,5),100)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [100]:
a=np.full((4,8),"ms")
a

array([['ms', 'ms', 'ms', 'ms', 'ms', 'ms', 'ms', 'ms'],
       ['ms', 'ms', 'ms', 'ms', 'ms', 'ms', 'ms', 'ms'],
       ['ms', 'ms', 'ms', 'ms', 'ms', 'ms', 'ms', 'ms'],
       ['ms', 'ms', 'ms', 'ms', 'ms', 'ms', 'ms', 'ms']], dtype='<U2')

In [101]:
np.full_like(a,15)

array([['15', '15', '15', '15', '15', '15', '15', '15'],
       ['15', '15', '15', '15', '15', '15', '15', '15'],
       ['15', '15', '15', '15', '15', '15', '15', '15'],
       ['15', '15', '15', '15', '15', '15', '15', '15']], dtype='<U2')

## eye

- Return a 2-D array with ones on the diagonal and zero elsewhere.

In [102]:
np.eye(5,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [103]:
np.eye(5,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

In [104]:
np.eye(10,10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [105]:
np.eye(5,k=3)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [106]:
np.eye(10,k=-2)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]])

## Where

In [108]:
z=np.arange(3,50)
z

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
np.where(z<15)

#it gives position of that element witch satisfy the condition

In [110]:
np.where(z%2==0)

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
        35, 37, 39, 41, 43, 45], dtype=int64),)

In [111]:
np.where(z==6)

(array([3], dtype=int64),)

### Split

- Split an array into multiple sub-array

In [112]:
e=np.arange(0,10)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
np.split(e,5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [114]:
np.split(e,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [115]:
a,b=np.split(e,2)

In [116]:
a

array([0, 1, 2, 3, 4])

In [117]:
b

array([5, 6, 7, 8, 9])

### Arithematic Operations in numpy

In [ ]:
import numpy as np

In [118]:
a=np.array([[1,2,10],[5,7,8]])
b=np.array([[10,20,7],[50,70,7]])

In [119]:
a

array([[ 1,  2, 10],
       [ 5,  7,  8]])

In [120]:
b

array([[10, 20,  7],
       [50, 70,  7]])

### add()

In [121]:
a+b   #using operators(+)

array([[11, 22, 17],
       [55, 77, 15]])

In [122]:
np.add(a,b)

array([[11, 22, 17],
       [55, 77, 15]])

### sub()

In [123]:
np.subtract(a,b)

array([[ -9, -18,   3],
       [-45, -63,   1]])

### mult()

In [124]:
np.multiply(a,b)

array([[ 10,  40,  70],
       [250, 490,  56]])

In [126]:
a=np.array([[1,2,3],[2,3,4]])
b=np.array([[1,2,3],[2,3,4]])


In [127]:
a*b

array([[ 1,  4,  9],
       [ 4,  9, 16]])

In [128]:
np.divide(a,b)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [129]:
np.mod(a,b)

array([[0, 0, 0],
       [0, 0, 0]])

In [130]:
np.power(a,b)

array([[  1,   4,  27],
       [  4,  27, 256]])

### Statistics

In [131]:
import numpy as np

In [132]:
s=np.array([[50,10,30,],[500,100,300,],[5,1,3,]])
s.ndim

2

In [133]:
s

array([[ 50,  10,  30],
       [500, 100, 300],
       [  5,   1,   3]])

In [134]:
b=np.array([[50,17,4],[50,140,0],[15,1,3]])
b

array([[ 50,  17,   4],
       [ 50, 140,   0],
       [ 15,   1,   3]])

In [135]:
np.amax(b,axis=1)       #0=row,1=col

array([ 50, 140,  15])

In [136]:
np.amin(s,axis=0)

array([5, 1, 3])

In [137]:
np.amax(s)

500

In [138]:
np.amax(s,axis=0)

array([500, 100, 300])

In [139]:
np.amax(s,axis=1)

array([ 50, 500,   5])

In [140]:
b

array([[ 50,  17,   4],
       [ 50, 140,   0],
       [ 15,   1,   3]])

In [141]:
np.mean(b)

31.11111111111111

In [142]:
(50+50+15+17+140+1+4+3)/9

31.11111111111111

In [143]:
np.var(s)

26960.666666666668

In [144]:
np.std(s)

164.1970361080451

### Datatype

- The main several data types supported by NumPy Python are
- np.bool_: This type is used to return boolean values like (True or False).
- np.int: It is the default type of integer and C-type long.
- intc: It is similar to C integer and it indicates 32 or 64 bit integer.
- intp: This type indicates for indexing.
- int8: By default its range value is -128 to 127.
- int16: It is a 16 bit integer and by default its range value is (-32768 to 32767).
- int32: it is for set 32-bit integer and the range value is (-2147483648 to 2147483647).
- int64: By default its value is set at (-9223372036854775808 to 9223372036854775807).
- uint8: It is a 8 bit integer and range value is (0 to 255).
- uint16: It is a 16 bit unsigned integer and range value is (0 to 65535).
- uint32: This is a unsigned integer with 32 bit and its value is (0 to 4294967295).
- uint64: It is a 8 byte unsigned integer and range value is (0 to 18446744073709551615).

In [161]:
a=np.array([2555])
a.dtype


dtype('int32')

In [162]:
a=np.array([12,2,3,6],dtype=np.float16)

In [163]:
a.dtype

dtype('float16')

In [164]:
a

array([12.,  2.,  3.,  6.], dtype=float16)

In [165]:
np.array(np.datetime64('1999-06-14'))

array('1999-06-14', dtype='datetime64[D]')

In [166]:
new=np.array([1.0,2.0,3.0])
new

array([1., 2., 3.])

In [168]:
b=np.array([1,2,3])

In [169]:
b.astype("str")

array(['1', '2', '3'], dtype='<U11')

In [170]:
b.astype("f")

array([1., 2., 3.], dtype=float32)

In [171]:
np.iinfo(np.int8).max

127

In [172]:
np.iinfo(np.int8).min

-128